# frozen_string_literal: true

# Strings

# Numerical types

# Boolean

# Simbols => In C++ <enum class>, Python<String internals>
on = :on
off = :off
waiting = :waiting

# puts((true if animal == animal_2))
print("#{on.upcase}\n") # => Doesn't add a new line.
print("#{off.upcase}\n")
puts(waiting.capitalize) # => Adds a new line.

# Classes
class Item
  # attr_reader
  attr_reader :id
  attr_reader :age

  # attr_accessor
  attr_accessor :name
  attr_accessor :country

  # Class vars.
  @@id_counter = 0

  def initialize(name, age, country)
    # Instance vars.
    @name = name
    @age = age
    @country = country
    @@id_counter += 1
    @id = @@id_counter
  end

  def print_data
    puts("Los datos de este Item son:\n
      [Nombre]: #{name.upcase} | Edad: #{age}\n
      [País]: #{country} | ID: #{id}")
  end
end

bag = Item.new('Bolsita', 23, 'Colombia')

# Getters generated by Ruby Macros attr_
# puts bag.name.upcase
# puts bag.age
# puts bag.country
# print("\n")

puts(bag.print_data)

# Setters generated by Ruby Macros attr_
bag.name = 'Funda'
bag.country = 'RD'

# Multi line comments

=begin
This is
a multi
line comment.

Rubocop doesn't recommend them, but they'll be useful at some point.
=end

# puts bag.name.upcase
# puts bag.age
# puts bag.country

# Instance Methods
puts(bag.print_data)

# Operadores aritméticos
# Operadores lógicos
# Operadores de comparación
